basePath: /
definitions:
  api.errResponse:
    properties:
      error:
        type: string
    type: object
  model.Task:
    properties:
      comment:
        type: string
      date:
        type: string
      id:
        type: string
      repeat:
        type: string
      title:
        type: string
    type: object
  model.TaskResp:
    properties:
      id:
        type: integer
    type: object
  model.TasksResp:
    properties:
      tasks:
        items:
          $ref: '#/definitions/model.Task'
        type: array
    type: object
host: http://localhost:7540
info:
  contact:
    email: spdante@mail.ru
    name: Alexey Yudin
  description: Итоговый проект (Яндекс Практикум)
  termsOfService: spdante@mail.ru
  title: Пользовательская документация API
  version: 1.0.0
paths:
  /api/task:
    delete:
      consumes:
      - application/json
      description: Удалить задачу
      parameters:
      - description: Идентификатор задачи
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Удалить задачу
      tags:
      - Task
    get:
      consumes:
      - application/json
      description: Получить задачу
      parameters:
      - description: Идентификатор задачи
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Получить задачу
      tags:
      - Task
    post:
      consumes:
      - application/json
      description: Выполнить задачу
      parameters:
      - description: Идентификатор задачи
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Выполнить задачу
      tags:
      - Task
    put:
      consumes:
      - application/json
      description: Редактировать задачу
      parameters:
      - description: Идентификатор задачи
        in: body
        name: id
        required: true
        schema:
          type: string
      - description: Дата задачи
        in: body
        name: date
        required: true
        schema:
          type: string
      - description: Заголовок задачи
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: Комментарий к задаче
        in: body
        name: comment
        required: true
        schema:
          type: string
      - description: Правило повторения
        in: body
        name: repeat
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Редактировать задачу
      tags:
      - Task
  /api/tasks:
    get:
      consumes:
      - application/json
      description: Получить список ближайших задач
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TasksResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Получить список ближайших задач
      tags:
      - Task
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
